### ISSUE TITLE
好多demo都跑不起来了

### ISSUE THREAD

**Issue by leavegee** [huangjia2019/langchain#1]
很多引入的库版本都是老的. 用最新的都跑不起来.
希望老师增加requestments.txt文件, 指明可用的依赖版本

**Comment by huangjia2019** [comment]
嗯呢嗯呢，肯定有这个问题。LangChain变化实在太快了。我应该增加这个文件requestments.txt。目前太忙了。有空就弄。同学先学着概念。代码版本变，概念不变。

**Comment by huangjia2019** [comment]
好了，我已经把requirements.txt发上来了。如果环境还有一些问题。再让我知道吧。
很多Warning，无所谓了，变成Error再说。
